services:
  bot:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: qbittorrent-bot
    restart: unless-stopped
    depends_on:
      - cache
    environment:
      - QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./qbittorrent-bot-data:/app/data

  cache:
    image: redis:8
    container_name: redis-cache
    restart: unless-stopped
